# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-18.04-virtualbox.box"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "lamp"
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "lamp"
  config.vm.define :lamp do |lamp|
  end

  config.vm.network :private_network, ip: "192.168.33.33"
  config.vm.network "forwarded_port", guest: 22, host: 22022
  config.vm.network "forwarded_port", guest: 80, host: 22080
  config.vm.network "forwarded_port", guest: 443, host: 22443
  config.vm.network "forwarded_port", guest: 3306, host: 22306

  # config.vm.provision "chef_zero" do |chef|
  #   chef.arguments = '--chef-license accept'
  #   chef.cookbooks_path = "cookbooks"
  #   chef.nodes_path = "nodes"

  #   chef.add_recipe "hello_web"
  # end

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/inventory"
    ansible.become = true
  end
end
