---
# tasks file for ntp
- name: configure timezone
  timezone:
    name: "{{ timezone }}"
  notify: reconfigure tzdata

- name: install tzdata
  apt: pkg=tzdata state=present

- name: install ntp
  apt: pkg=ntp state=present

- name: start ntp
  service: name=ntp state=started enabled=true

- name: set ntp server
  lineinfile: dest=/etc/ntp.conf state=present regexp='^server ' line='server {{ ntp_server }} iburst'
  notify: restart ntp

- name: remove all other ntp servers
  lineinfile: dest=/etc/ntp.conf state=absent regexp="^server\s+(?!{{ ntp_server }})"
  notify: restart ntp

- name: Ensure NTP is running and enabled as configured.
  service:
    name: ntp
    state: started
    enabled: true
  when: ntp_enabled | bool