version: "3"

services: 
  balancer:
    image: nginx:latest
    ports:
      - 80:80/tcp
      - 81:8080/tcp
    networks: 
      - site1
      - site2
    depends_on: 
      - web
      - tomcat
    volumes:
        #- ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
        - ./nginx.conf:/etc/nginx/nginx.conf:rw

  web:
    build: ../Dockerfile_task
    volumes: 
      - ./web/etc/sites-enabled:/etc/apache2/sites-enabled
      - ./web/www:/var/www/site
    #depends_on: 
      #- mysql57
    networks: 
      - site1
      - database
  
  tomcat:
    image: tomcat:latest
    networks: 
      - site2

  mysql57:
    image: percona:5.7
    environment: 
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - "./mysql/configs/my.cnf:/etc/mysql/conf.d/custom.cnf:rw"
      - "/home/roman/DevOps/1_Containers/Docker/Docker-compose/mysql/mysql:/var/lib/mysql:rw"
    networks: 
      - database

networks: 
  site1:
  site2:
  database: