version: "3.8"
services: 
  balancer:
    image: nginx:latest
    ports:
    - 80:80/tcp
  web:
    build: ../Dockerfile_task
    volumes: 
    -
    -
  mysql57:
    image: percona:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
    volumes: 
    -
    -