version: "3"

services: 
  balancer:
    image: nginx:latest
    ports:
      - 80:80/tcp
    networks: 
      - site1
      - site2
    depends_on: 
      - web
      - tomcat
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:rw

  web:
    build: ../Dockerfile_task
    volumes: 
      - ./web/etc/sites-enabled:/etc/apache2/sites-enabled
      - ./web/www:/var/www/site
    depends_on: 
       - mysql
    networks: 
      - site1
      - database
  
  tomcat:
    build: ./tomcat
    networks: 
      - site2

  mysql:
    image: percona:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: new_base
    volumes: 
      - "./.mysql-data/db:/var/lib/mysql"
    networks: 
      - database

networks:
  site1:
  site2:
  database: