
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-18.04-virtualbox.box"

  config.vm.provider :virtualbox do |v|
    v.name = "ab"
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "ab"
  config.vm.define :ab do |ab|
  end
end
